### ISSUE TITLE
[Feature] Add more flexibility

### ISSUE THREAD

**Issue by BoxedBrain** [blueswen/mkdocs-glightbox#2]
Hi,

it would be great to control the behavior for specific images using the [attribute-list syntax](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists) in combination with some global options, or even by page using the [metadata option](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#metadata).

For example, having the ability to:
- enable the light box globally or by page and disable for specific images
- disable globally or by page and enable for specific images

**Comment by blueswen** [comment]
I had thought about this feature before, but I didn't implement this to keep this plugin simple at first. Glad to hear someone need this too.

I will add this feature later. Thanks for the advice and great ideas 😄.

**Comment by blueswen** [comment]
Hi @BoxedBrain,

we are support disabling lightbox by a [specific image](https://blueswen.github.io/mkdocs-glightbox/disable/image/) or a [specific page](https://blueswen.github.io/mkdocs-glightbox/disable/page/) since v0.2.0. Thanks for the ideas, they save me a lot of time, but I only implemented disabling logic to keep this plugin setting as simple as possible.

If there is anything advice for this new feature just let me know 😊.
