### ISSUE TITLE
[Feature Request] Support transparency

### ISSUE THREAD

**Issue by couleurm** [blueswen/mkdocs-glightbox#27]
Hey, would it feasible to support transparency in in images (e.g on PNGs and SVGs)? Thank you!

**Comment by blueswen** [comment]
Hi @couleurm. Do you mean keeping the PNG or SVG files background transparent instead of a white background?

The effect with the transparency background in the slide looks as follows:
<img width="1057" alt="Transparent" src="https://github.com/blueswen/mkdocs-glightbox/assets/1564148/744ac187-d7ee-4d0d-8f3b-3e81c6d195a5">

Currently, this plugin will add a white background automatically that looks as follows:
<img width="1235" alt="White" src="https://github.com/blueswen/mkdocs-glightbox/assets/1564148/e965ecdc-3c05-4959-a2c5-277a5e1402e3">

**Comment by couleurm** [comment]
that drop shadow makes it really explicit where the picture ends, can that also be configured?
![image](https://github.com/blueswen/mkdocs-glightbox/assets/82747632/83255301-bfb7-46ff-912b-57b3c53b5567)

**Comment by couleurm** [comment]
what type of value can be put in background? it'd be cool to have rgba

**Comment by blueswen** [comment]
You can check details on [document](https://blueswen.github.io/mkdocs-glightbox/#:~:text=top%2C%20left%2C%20right%29-,background,-white). Any valid CSS value for background is fine.
